apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: erikflux
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: geddes-registry.rcac.purdue.edu/docker-hub-cache/library/nginx
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
