apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: erikflux
  annotations:
    metallb.universe.tf/address-pool: geddes-private-pool
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
